### ISSUE TITLE
Adding controls as options

### ISSUE THREAD

**Issue by KiLLeRRaT** [iambumblehead/react-dropdown-now#105]
Hi,

We are using the dropdown, to display options that have sub controls, so imagine a menu that opens, and each of the items has a `+`, and `-` buttons, and a textbox in the middle.  This is used to adjust quantities. This all works and displays nicely.

The problem we are facing is that whenever you click on anything on the option, the menu closes.  Is there a way that we can prevent this behavior? We have a `Select` button at the bottom which the user clicks to close the dropdown.

Any help would be appreciated.

Cheers,

**Comment by iambumblehead** [comment]
@KiLLeRRaT have you tried "preventing" the event from within elements childed to the dropdown with something like this? `onClick = e => e.preventDefault();` I'm not certain if this would solve the issue for you, but it might.

**Comment by KiLLeRRaT** [comment]
Hi @iambumblehead thanks for coming back to me.

Hmm I don't think that works.  Here is a basic working example I've set up which you can try if you have any other ideas.

[https://codesandbox.io/s/react-playground-forked-1nr35?file=/index.js](https://codesandbox.io/s/react-playground-forked-1nr35?file=/index.js)

Here is the code for it:

```
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import { Dropdown } from "react-dropdown-now";
import "react-dropdown-now/style.css";

export default function Search() {
  function button_click(e) {
    console.log("button_click");
    e.preventDefault();
    e.stopPropagation();
  }

  let passengerOptions = [];
  let passengerElement = (
    <div>
      <button type="button" onClick={button_click}>
        button
      </button>
      &nbsp;my element
    </div>
  );
  passengerOptions.push({ id: "1", label: "label 1", view: passengerElement });
  passengerOptions.push({ id: "2", label: "label 2", view: passengerElement });
  passengerOptions.push({ id: "3", label: "label 3", view: passengerElement });

  return (
    <div>
      <h1>Hello world</h1>
      <Dropdown
        placeholder="Select passengers"
        options={passengerOptions}
        value=""
        onSelect={function (option, e) {
          e.preventDefault();
          e.stopPropagation();
        }}
      />
    </div>
  );
}

ReactDOM.render(<Search />, document.getElementById("container"));

```

Thanks again,

**Comment by iambumblehead** [comment]
@KiLLeRRaT just now I looked at this file https://github.com/iambumblehead/react-dropdown-now/blob/master/src/components/Option.tsx#L45-L47

after that I tried this in the sandbox demo you shared
```jsx
<button
    type="button"
    onClick={button_click}
    onKeyDown={e => e.stopPropagation()}
    onMouseDown={e => e.stopPropagation()}
>button</button>
```
After adding onKeyDown and onMouseDown stopPropagation, the dropdown stays open when clicking the button. How does it work for you?

cc @lwhiteley for your interest

**Comment by KiLLeRRaT** [comment]
Hi @iambumblehead,

Thanks for that, it works as we want it to work :)

What we're working towards is having a `+` and `-` button, with a textbox for QTY, and at the end of the select box, have a `Close` button.  The  `+` and `-` buttons work now, but with the input, there is still no way to type into it, it keeps closing :)

I'm starting to wonder if it would be handy to have some sort of open/close state exposed on the dropdown, so that you can open and close it programatically from outside of it's own code.

Thanks for helping out,

**Comment by KiLLeRRaT** [comment]
Hi @iambumblehead ,

We have since actually found that we can use the menu prop, and pass through our entire container.  This works exactly how we want it to work now :)

Thanks for the help!

Regards,

**Comment by iambumblehead** [comment]
@KiLLeRRaT awesome thanks for looping me in!
