### ISSUE TITLE
Bug! Module not found: Can't resolve './Dropdown'

### ISSUE THREAD

**Issue by rscotten** [iambumblehead/react-dropdown-now#11]
Hello, thanks for making this fork of `react-dropdown`.

I was using version `1.0.3` and everything was working fine, now the latest version is causing this error:

```
~/myRepo/node_modules/react-dropdown-now/dist/index.js
Module not found: Can't resolve './Dropdown' in '~/myRepo/node_modules/react-dropdown-now/dist'
```

Please help.

**Comment by lwhiteley** [comment]
@iambumblehead seems the module isnt build properly when you released.

https://www.jsdelivr.com/package/npm/react-dropdown-now?path=dist

`Dropdown.js` is actually missing from the folder

**Comment by lwhiteley** [comment]
@iambumblehead it still does not have the Dropdown file in the dist folder ..

can you run `npm run build` and ensure the dist folder has two file

**Comment by iambumblehead** [comment]
I did npm run build and git did not find any changes. dist/Dropdown.js is present.

**Comment by lwhiteley** [comment]
yea git should find any changes

but the file is not being pushed to npm for some reason

**Comment by lwhiteley** [comment]
Can you make me a Collaborators on the npm package as well and let me try to push and see..

username: lwhiteley

**Comment by iambumblehead** [comment]
@lwhiteley you've been added :)

**Comment by lwhiteley** [comment]
oo i meant add me as a collaborator on the package itself
 https://www.npmjs.com/package/react-dropdown-now

**Comment by lwhiteley** [comment]
<img width="1220" alt="Screenshot 2020-02-15 at 19 26 11" src="https://user-images.githubusercontent.com/6108793/74593204-200fa980-5029-11ea-90a9-c1a7a4191ef8.png">

**Comment by iambumblehead** [comment]
![maintainers](https://user-images.githubusercontent.com/2058705/74593222-dcdc1900-4fdd-11ea-93f8-71f29f0a7377.png)

**Comment by iambumblehead** [comment]
@lwhiteley try logging out of and back into npm

**Comment by iambumblehead** [comment]
@lwhiteley I believe this is caused by the 'files' directive in the package.json

**Comment by lwhiteley** [comment]
ah i see let me try to fix it

**Comment by iambumblehead** [comment]
@lwhiteley thank you. npm should allow you to publish the changes.

**Comment by lwhiteley** [comment]
ok i see you already did it..so ill try to release some other time

**Comment by lwhiteley** [comment]
@rscotten all should be fine now with v1.0.9 on npm

**Comment by rscotten** [comment]
@lwhiteley That worked.  Thank you! :)
