### ISSUE TITLE
use custom action for gh-pages

### ISSUE THREAD

**Issue by lwhiteley** [iambumblehead/react-dropdown-now#20]
this requires some simple steps and worth it.
with this you can remove the need to build the docs/bundle.js and store it in the repository.

you can also disable the current gh-pages setting that is pointed to the docs folder for the repo as well.

(leave enabled but ensure we can do a custom deploy i assume)

- [ ] https://github.com/peaceiris/actions-gh-pages#getting-started
- [x] https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-react-and-next

**Comment by iambumblehead** [comment]
the deploy keys are added

**Comment by lwhiteley** [comment]
ok ill try to test it on the current pr branch first

**Comment by lwhiteley** [comment]
doesnt seems worth it.
the only branch that seems to work is the master branch.

will close
