### ISSUE TITLE
make develop default branch

### ISSUE THREAD

**Issue by lwhiteley** [iambumblehead/react-dropdown-now#24]
@iambumblehead 

I created a `develop` branch. Can you make this the default branch and ensure both `master` and `develop` are protected branches.

Reason:
- Only master can deploy to gh-pages
- if we are rapidly developing, and merging to master all the time then it is possible the website will not reflect the the features deployed to npm
- So with default branch `develop` we can continue merging stuff and only merge to master when we are doing a release.

<img width="305" alt="Screenshot 2020-02-20 at 18 36 16" src="https://user-images.githubusercontent.com/6108793/74962319-f59a6380-540f-11ea-9bfb-fa68da1e7393.png">

let me know if that makes sense

**Comment by iambumblehead** [comment]
@lwhiteley that is a terrific plan
