### ISSUE TITLE
demo document uses wrong npm install command

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#36]
[The demo document shows][0] this (should be react-dropdown-now)
```bash
$ npm install react-dropdown --save
```
I'm not sure this install command even needs to be included in the demo document. If there's not a reason to keep it, let's remove it altogether.

[0]: https://iambumblehead.github.io/react-dropdown-now/

**Comment by lwhiteley** [comment]
can be updated to 

```
npm i --save react-dropdown-now 
```
