### ISSUE TITLE
discuss classNames

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#37]
Following up [from the discussion here...][0] this component could provide classNames needed for styling elements in the dropdown in different states without [supporting several custom className attibutes for different elements.][1]

The markup could look something like this, where "fire" is a custom className defined by the parent and applied to all dropdown elements, and "open" is applied when the dropdown is in an open state,
```html
<div class="fire open dropdown">
  <div class="fire open dropdown-placeholder">placeholder</div>
  <div class="fire open dropdown-control">
    <div class="fire open dropdown-control-option">option</div>
  </div>
</div>
```
This change would remove custom className attributes and simplify the interface.

If we decide to make this change, it should probably be made after the next release and not before.

[0]: https://github.com/iambumblehead/react-dropdown-now/pull/23#pullrequestreview-359545508
[1]: https://github.com/iambumblehead/react-dropdown-now/blob/develop/src/Dropdown.js#L100-L122

**Comment by iambumblehead** [comment]
@rscotten I would would glad to know your opinion about this

**Comment by rscotten** [comment]
@iambumblehead Fine with me.  I wouldn't have to duplicate my CSS as much for different dropdown components with different `baseClassName`s.

**Comment by lwhiteley** [comment]
when changed.. just an FYI .. see how [react-sanfona](https://github.com/daviferreira/react-sanfona) documents their classnames

![Screenshot 2020-02-25 at 11 04 52](https://user-images.githubusercontent.com/6108793/75236928-ce041c00-57be-11ea-8418-ee513750121c.png)

**Comment by iambumblehead** [comment]
I'm interested in doing this before adding support for more options such as https://github.com/iambumblehead/react-dropdown-now/issues/68

The reason is, it will reduce the number of configuration options needing README descriptions.

**Comment by iambumblehead** [comment]
this is implemented --closing
