### ISSUE TITLE
removing docs/bundle.js from git sources

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#41]
**docs/bundle should be auto-generated** by CI somehow. Since you tried setting up a similar process earlier you may have further ideas, @lwhiteley. Some ideas: we could try using a travis.ci pipeline to build the bundle and docs (not sure if this is doable), we could remove the interactive docs that use the bundle and use a static README with screenshots, we could move this project to gitlab and a gitlab pipeline could do this with low effort (personal experience). What do you think?

**Comment by lwhiteley** [comment]
we can use github actions to build on merge to master

**Comment by iambumblehead** [comment]
ok I'll focus attention on github actions for that

**Comment by iambumblehead** [comment]
related: https://github.com/iambumblehead/react-dropdown-now/pull/21

**Comment by lwhiteley** [comment]
here an idea from [react-table](https://github.com/tannerlinsley/react-table/blob/HEAD/docs/examples.md)

**Comment by lwhiteley** [comment]
@iambumblehead consider moving the a site like netlify.. that way we can remove the docs from source and only use one branch for integration

- https://www.netlify.com/
- https://vercel.com/

**Comment by lwhiteley** [comment]
gh-pages also started again to allow you to specify branch for deployment..we can also try that first ...

i will create a branch called gh-pages and create a github action to deploy to it

**Comment by iambumblehead** [comment]
the gh-pages storybook is excellent
