### ISSUE TITLE
discuss README simplifications

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#42]
@lwhiteley I'm interested in shortening the README to, essentially, a few lines --a single getting-started code sample with little or no explanation and a link to the doc page for more info. If you like the current README I won't plan changes to it.

For example, this style of README https://github.com/iambumblehead/form-urlencoded

**Comment by lwhiteley** [comment]
that is a good idea. go ahead

**Comment by iambumblehead** [comment]
@lwhiteley the current README is pretty good and maybe we should close this. If the README were edited, these would be the changes I would make and I'm not sure if you would agree with them so am sharing them here for you to know if you disagree or agree with them...
 * remove minimum react version notice,
 * remove 'matcher' demonstration. matcher could be in a more detailed document which might be found in the storybook pages. The matcher behaviour seems like an advanced option. If it were included in the README, a more instructive demonstration should be there showing an example case where the matcher would be useful
 * combine most sections into the main code example that starts at the top of the readme...

for the last point, I think many parts of the README could be consolidated into the code example sort of like this,
```javascript
<Dropdown
  className-"dropdown-with-simple-options"
  ...
/>

<Dropdown
  className="dropdown-with-complex-options"
  ...
/>

<Dropdown
  className="dropdown-with-grouped-options"
  ...
/>

<Dropdown
  className="dropdown-disabled"
  disabled
  ...
/>

<Dropdown
  className="dropdown-with-custom-arrow"
```

I'm not sure the README needs details about the event values. The follow would be OK for me but you may not agree (in which case it is good keep things as they are),
```javascript
<Dropdown
  className="dropdown-with-simple-options"
  placeholder="Select an option"
  options="{['one', 'two', 'three']}"
  value="one"
  onChange={value => console.log(value)}
  onSelect={value => console.log(value)}
  onClose={value => console.log(value)}
  onOpen={() => console.log('open')}
```

**Comment by lwhiteley** [comment]
I'm thinking a lot of it should end up in the storybook site..I'll look
into it but yea we can close for now
