### ISSUE TITLE
onChange not called with event object

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#51]
1.0.0 dropdown returns an event and the 2.0.0  dropdown returns a velue

so that this
```
 onChange={onChange}
```
needs to be changed to this in order to remain _somewhat_ compatible with 1.0.0
```
onChange={value => onChange({ value })}
```
the 1.0.0 version is better imo, because emitting the full event gives the handler more control over both the value and the event

**Comment by lwhiteley** [comment]
prefer 

```js
onChange={event => onChange(value, event)}
```

event as second argument as the old version never returned an event
https://github.com/fraserxu/react-dropdown/blob/master/index.js#L94

**Comment by lwhiteley** [comment]
if you mean always returning an object instead of potentially a string/number, that is a different case

**Comment by iambumblehead** [comment]
you are right @lwhiteley
