### ISSUE TITLE
selecting grouped values results in an empty label

### ISSUE THREAD

**Issue by iambumblehead** [iambumblehead/react-dropdown-now#52]

**Comment by lwhiteley** [comment]
i was able to reproduce the empty label but it had nothing to do with grouped results

When `option.value` is not a string then the dropdown component is broken.

label is empty and the `onChange` function doesn't return an object with `{value, label}`.

<img width="986" alt="Screenshot 2020-04-29 at 21 20 10" src="https://user-images.githubusercontent.com/6108793/80637403-3d1c1c00-8a5f-11ea-9655-3e4363edccb0.png">

**Comment by iambumblehead** [comment]
@lwhiteley that is useful to know. I don't know when I will be available to resolve it, but it will be easier to resolve knowing that.

**Comment by lwhiteley** [comment]
ill take a look at it and while im at it, simplify the code.

it may involve breaking changes so lets see if we need to plan a `v3.0.0` release
