### ISSUE TITLE
Is there a way to clear a dropdown value?

### ISSUE THREAD

**Issue by rtyurin** [iambumblehead/react-dropdown-now#67]
The title says it. 
It seems like there is no way to reset dropdown value, so the dropdown will show placeholder again. [example](https://codesandbox.io/s/prod-fast-hczbz) - tried to illustrate it here, `value` in state goes undefined as you click on `Reset` button, but dropdown will still show you the previous value. Possibly because of [this line of code](https://github.com/iambumblehead/react-dropdown-now/blob/develop/src/Dropdown.js#L95).

**Comment by iambumblehead** [comment]
@rtyurin thanks for finding this bug. If you submit a PR it will be accepted, otherwise I'll resolve it when I have more time maybe this weekend.

**Comment by iambumblehead** [comment]
@lwhiteley I will likely try to address this today and if you're around to review my changes that would be awesome

**Comment by iambumblehead** [comment]
I'll make a PR to resolve this issue after this dependency-updating MR is approved and merged https://github.com/iambumblehead/react-dropdown-now/pull/70
