### ISSUE TITLE
return master as main branch

### ISSUE THREAD

**Issue by lwhiteley** [iambumblehead/react-dropdown-now#79]
related to #78 

- [x] first ensure master is not a protected branch

command to use:

```bash
git checkout develop
git pull
git push origin :master          # delete master on remote
git branch -D master # ensure local master is deleted as well
git checkout -b master # create a new local master from develop
git push origin master           # push new master to remote
```

- [x] in repository settings switch main branch from develop to master
- [x] make develop unprotected.
- [x] clean up unnecessary branches

**Comment by iambumblehead** [comment]
looking at this now

**Comment by iambumblehead** [comment]
these things are done and develop branch is removed. there seems to be a pipeline error on master
