### ISSUE TITLE
Error + fix in dropdown-now/style.css

### ISSUE THREAD

**Issue by GoetheProductions** [iambumblehead/react-dropdown-now#92]
Hey
I spend a good amount of my day trying to solve an error when running `npm run build` in `create-react-app` setup.

Here is the error: 
```
Cannot divide by "px", number expected
CompileError: Begins at CSS selector undefined
```

It turns out that the error comes from `react-dropdown-now/style.css` in the following class:

```
.rdn-control-clear-button-icon:before,
.rdn-control-clear-button-icon:after {
  position: absolute;
  left: calc(var(--clear-button-icon-width) / 2px);
  content: ' ';
  height: calc(var(--clear-button-icon-width) + 3px);
  width: 2px;
  background-color: var(--icon-color);
}
```

The calc arguments should not have units. so to fix the issue it should look like this:
```
.rdn-control-clear-button-icon:before,
.rdn-control-clear-button-icon:after {
  position: absolute;
  left: calc(var(--clear-button-icon-width) / 2);
  content: ' ';
  height: calc(var(--clear-button-icon-width) + 3);
  width: 2px;
  background-color: var(--icon-color);
}
```

Thank you for a nice module btw.

**Comment by lwhiteley** [comment]
Thanks for pointing this out, would you mind submitting a pull request?

**Comment by lwhiteley** [comment]
v5.0.0 released

cc: @tamirGer @iambumblehead
